# Generated by Django 4.2.3 on 2024-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='bar_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.CharField(max_length=30)),
                ('obj3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='line_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.CharField(max_length=30)),
                ('obj3', models.CharField(max_length=30)),
                ('obj4', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='objects_bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.FloatField()),
                ('obj3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='objects_line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='objects_pie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.FloatField()),
                ('obj3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='pie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj1', models.CharField(max_length=30)),
                ('obj2', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='objects2',
        ),
    ]
