# Generated by Django 4.2.10 on 2024-03-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_allimagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllImageModel',
        ),
    ]
