# Generated by Django 4.2.10 on 2024-03-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0005_delete_allimagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('image_field', models.ImageField(upload_to='images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
